<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body><table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="thwecmf_template_wrapper"><tr><td align="center" class="thwecmf-template-wrapper-column" valign="top" style="background-color: #f7f7f7; padding: 70px 0;"><table id="tpf_t_builder" width="600" cellspacing="0" cellpadding="0" class="thwecmf-main-builder thwecmf-template-block" style="max-width: 600px; width: 600px; margin: auto;"><tr><td class="thwecmf-builder-column" style="vertical-align: top; border-radius: 2px; background-size: cover; background-repeat: no-repeat; background-position: top; border-style: solid; border-color: #dedede; background-color: #ffffff; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px;">
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1010" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-style: none; border-color: transparent; background-color: transparent; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1011" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; border-style: none; border-color: #dddddd; background-color: #c57719; text-align: left; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;"><table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1029" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #ffffff; font-size: 22px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #ffffff; font-size: 22px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #ffffff; font-size: 22px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #ffffff; font-size: 22px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Thanks for shopping with us<br style="color: #ffffff; font-size: 22px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table></td></tr></table>
<table class="thwecmf-row thwecmf-block-two-column thwecmf-builder-block" id="tpf_1032" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-style: none; border-color: transparent; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"><tr>
<td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1033" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 50%; border-style: dotted; border-color: #dddddd; background-color: transparent; text-align: center; background-image: none; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;"><table class="thwecmf-block thwecmf-block-image thwecmf-builder-block" id="tpf_1035" cellspacing="0" cellpadding="0" align="center" style="table-layout: fixed; width: 100%; height: auto; max-width: 600px; box-sizing: border-box; background-color: transparent;">
		<tr>
			<td class="thwecmf-block-child thwecmf-image-column" style="padding: 0; box-sizing: border-box; vertical-align: middle; line-height: 0; text-align: left;"><p style="padding: 10px 0px; margin: 0; display: inline-block; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: transparent; width: 75%; height: auto; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;">
			<img src="https://stonewoodcollections.com.au/wp-content/uploads/2022/04/Attachment_1650336605.jpg" alt="Image" width="207.5" height="129.792" style="width: 100%; height: auto; max-width: 100%; max-height: 100%; display: block;">
		</p></td>
</tr>
</table></td>
<td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1034" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 50%; border-style: dotted; border-color: #dddddd; background-color: transparent; text-align: center; background-image: none; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;">
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1036" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 18px; line-height: 150%; font-weight: 800; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #636363; font-size: 18px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 18px; font-weight: 800; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 15px; padding-right: 15px; padding-bottom: 5px; padding-left: 15px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 18px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Stonewood Collections<br style="color: #636363; font-size: 18px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table>
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1037" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 13px; line-height: 150%; font-weight: 400; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">PO Box 1222 <br style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">North Lakes <br style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">QLD 4509<br style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Australia<br style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">ABN: 61 323 700 67<br style="color: #636363; font-size: 13px; font-weight: 400; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table>
</td>
</tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1038" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-style: none; border-color: transparent; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1039" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; text-align: center; border-style: dotted; border-color: #dddddd; background-color: transparent; background-image: none; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"><table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1040" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 22px; line-height: 150%; font-weight: 800; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #636363; font-size: 22px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 22px; font-weight: 800; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 22px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Tax Invoice<br style="color: #636363; font-size: 22px; font-weight: 800; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table></td></tr></table>
<table class="thwecmf-row thwecmf-block-one-column thwecmf-builder-block" id="tpf_1013" cellpadding="0" cellspacing="0" style="border-spacing: 0px; width: 100%; table-layout: fixed; max-width: 100%; margin: 0 auto; background-size: 100%; background-repeat: no-repeat; background-position: top; border-style: none; border-color: transparent; background-color: transparent; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto;"><tr><td class="thwecmf-column-padding thwecmf-col thwecmf-columns" id="tpf_1014" style="vertical-align: top; box-sizing: border-box; word-break: break-word; padding: 10px 10px; background-size: 100%; background-position: top; width: 100%; border-style: none; border-color: #dddddd; background-color: transparent; text-align: left; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;">
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1023" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 14px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 0px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Hi <?php if(isset($order)) : ?><?php echo esc_html($order->get_billing_first_name()); ?><?php elseif(isset($user_login)): ?><?php echo esc_html($user_login); ?><?php endif; ?>,<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;"><br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;"></div>
<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">We have finished processing your order.<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table>
<div class="thwecmf-hook-order-details"><?php if(isset($order)){ 
 					do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email ); 
 				}?></div>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
<?php if(isset($order)){ 
  					do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email ); 
  				}?>
<table class="thwecmf-block thwecmf-block-text thwecmf-builder-block" id="tpf_1031" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 100%; margin: 0 auto; box-sizing: border-box; color: #636363; font-size: 14px; line-height: 150%; font-weight: normal; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; margin-top: 0px; margin-right: auto; margin-bottom: 0px; margin-left: auto; text-align: left;">
		<tr style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
			<td class="thwecmf-block-child thwecmf-block-text-holder" style="vertical-align: top; box-sizing: border-box; padding: 15px 15px; background-size: cover; background-repeat: no-repeat; color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; text-align: left; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif; background-color: transparent; background-image: none; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-color: transparent; border-style: none; padding-top: 15px; padding-right: 0px; padding-bottom: 15px; padding-left: 0px;">
			<div class="wecmf-txt-wrap" style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">Thanks for shopping with us.<br style="color: #636363; font-size: 14px; font-weight: normal; line-height: 150%; font-family: 'Helvetica Neue',Helvetica,Roboto,Arial,sans-serif;">
</div>
			</td>
		</tr>
	</table>
</td></tr></table>
</td></tr></table></td></tr></table></body>
</html>
